batch_size: 32
config_type: benchmarks
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: cifar100
out_dir: run
predictor: params
search_space: nasbench201
seed: 9002
train_portion: 0.7
train_size: 100
