site_name: NASLib Documentation
site_url: https://github.com/automl/NASLib
nav:
    - Home: index.md
    - Installation: installation.md
    - Quick Start: quick_start.md
    - NAS Benchmarks:
        - Overview: benchmarks/overview.md
        - NAS-Bench-101: benchmarks/nasbench_101.md
        - NAS-Bench-201: benchmarks/nasbench_201.md
        - NAS-Bench-301: benchmarks/nasbench_301.md
    - Optimizers:
        - Overview: optimizers/overview.md
        - Discrete:
              - Random Search: optimizers/discrete/rs.md
              - Regularized Evolution: optimizers/discrete/re.md
              - Bananas: optimizers/discrete/bananas.md
        - One-Shot:
              - DARTS: optimizers/oneshot/darts.md
              - GDAS: optimizers/oneshot/gdas.md
              - DrNAS: optimizers/oneshot/drnas.md
              - RSWS: optimizers/oneshot/rsws.md

    - Search Spaces:
        - Overview: search_spaces/overview.md
        - NAS-Bench-101: search_spaces/nasbench_101.md
        - NAS-Bench-201: search_spaces/nasbench_201.md
        - DARTS Search Space: search_spaces/darts.md
        - NAS-Bench-ASR: search_spaces/nasbench_asr.md
        - NAS-Bench-NLP: search_spaces/nasbench_nlp.md
        - Simple Cell: search_spaces/simple_cell.md
        - Transbench101: search_spaces/transbench101.md
    - Utils:
        - Overview: utils/overview.md
        - Plotting: utils/plotting.md
        - Training Utilities: utils/training.md
    - Examples: examples.md
    - API Reference: api.md
    - Contributing: contributing.md
plugins:
  - mkdocstrings:
        enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
        custom_templates: templates
        default_handler: python
        handlers:
            python:
                options:
                    show_source: false
theme:
  name: "material"


