site_name: NASLib Documentation
site_url: https://github.com/automl/NASLib
nav:
    - Home: index.md
    - Setup: setup.md
    - Quick Start: quick_start.md
    - Optimizers:
        - Overview: optimizers/overview.md
        - Discrete:
              - Random Search: optimizers/discrete/rs.md
              - Regularized Evolution: optimizers/discrete/re.md
              - Bananas: optimizers/discrete/bananas.md
              - Base Predictor: optimizers/discrete/bp.md
              - Local Search: optimizers/discrete/ls.md
              - NPenas: optimizers/discrete/npenas.md
        - One-Shot:
              - DARTS: optimizers/oneshot/darts.md
              - GDAS: optimizers/oneshot/gdas.md
              - DrNAS: optimizers/oneshot/drnas.md
              - RSWS: optimizers/oneshot/rsws.md

    - Search Spaces:
        - Overview: search_spaces/overview.md
        - NAS-Bench-101: search_spaces/nasbench_101.md
        - NAS-Bench-201: search_spaces/nasbench_201.md
        - NAS-Bench-301: search_spaces/nasbench_301.md
        - NAS-Bench-ASR: search_spaces/nasbench_asr.md
        - NAS-Bench-NLP: search_spaces/nasbench_nlp.md
        - Simple Cell: search_spaces/simple_cell.md
        - Transbench101: search_spaces/transbench101.md
    # TODO Utils
    - Contributing: contributing.md

copyright: Copyright &copy 2023; NASLib contributors
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/automl
      name: AutoML Github

plugins:
  - mkdocstrings:
        enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
        custom_templates: templates
        default_handler: python
        handlers:
            python:
                options:
                    show_source: false
theme:
  name: "material"


