batch_size: 32
config_type: benchmarks
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: segmentsemantic
out_dir: run
predictor: epe_nas
search_space: transbench101_micro
seed: 9008
train_portion: 0.7
train_size: 100
