batch_size: 32
config_type: benchmarks
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: room_layout
out_dir: run
predictor: snip
search_space: transbench101_micro
seed: 9003
train_portion: 0.7
train_size: 100
