seed: 0
optimizer: bananas
search_space: nasbench201
dataset: cifar10
out_dir: run

search:
  seed: 0
  checkpoint_freq: 10 # 1000
  min_fidelity: 1
  fidelity: 200
  budgets: 4000
  eta: 2
  max_budget: 200
  min_budget: 1
  n_process: 1
  predictor_type: var_sparse_gp
