seed: 0
optimizer: bananas
search_space: nasbench201
dataset: cifar10
out_dir: run

search:
  seed: 0
  checkpoint_freq: 10 # 1000
  min_fidelity: 1
  fidelity: 200
  budgets: 4000
  eta: 3
  max_budget: 512
  min_budget: 12
  epsilon: 1e-6
  predictor_type: var_sparse_gp
  min_bandwith: 0.001
  top_n_percent: 0.1
  min_points_in_model: 7