onfig_id: 4
dataset: cifar10
optimizer: npenas
out_dir: run_cpu
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  checkpoint_freq: 5000
  debug_predictor: false
  encoding_type: path
  epochs: 400
  fidelity: -1
  k: 48
  max_mutations: 3
  num_arches_to_mutate: 2
  num_candidates: 32
  num_ensemble: 3
  num_init: 83
  population_size: 98
  predictor_type: var_sparse_gp
  sample_size: 88
search_space: asr
seed: 3
