config_id: 0
dataset: None
optimizer: sh
out_dir: run
search:
  acq_fn_optimization: mutation
  acq_fn_type: its
  budget_max: 128
  budget_type: epoch
  budgets: 16000
  checkpoint_freq: 5000
  crossover_prob: 0.5
  debug_predictor: false
  enc_dim: 6
  encoding_type: path
  epochs: 200
  epsilon: 1.0e-06
  eta: 2
  fidelity: 39
  k: 10
  max_budget: 39
  max_mutations: 1
  method: random
  min_bandwith: 0.001
  min_budget: 1
  min_fidelity: 1
  min_points_in_model: 7
  mutate_prob: 0.5
  n_process: 1000000
  num_arches_to_mutate: 1
  num_candidates: 50
  num_ensemble: 3
  num_init: 10
  number_archs: 128
  predictor_type: test
  population_size: 50
  predictor: var_sparse_gp
  sample_size: 10
  top_n_percent: 0.1
search_space: asr
seed: 0
