start_seed: 0
trials: 2
out_dir: run
out_dir_configs: configs

search_space: 
  - nasbench201
  - nasbench311
  - asr
datasets: 
  - cifar10
  - cifar100
  - ImageNet16-120
  - TIMIT
optimizers: # sh, rs, ls, ...
  - rs
  - ls
  - re
  - bananas
  - npenas
  - sh
  - hb
  - bohb
  - dehb

num_config: 2