start_seed: 0
trials: 1
out_dir: run
out_dir_config: configs
config_type: bbo-bs
search_space: nasbench201
datasets: 
  - cifar10
optimizers: # sh, rs, ls, ...
  - sh
fidelity: 200

HPO: True
# only relevant if HPO is enabled
num_config: 10

# for SH: 4
# for default BBOs: 200
epochs: 200

predictor: var_sparse_gp
