batch_size: 32
config_type: benchmarks
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: cifar10
out_dir: run
predictor: jacov
search_space: nasbench201
seed: 9008
train_portion: 0.7
train_size: 100
