batch_size: 32
config_type: benchmarks
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: autoencoder
out_dir: run
predictor: synflow
search_space: transbench101_macro
seed: 9006
train_portion: 0.7
train_size: 100
