name: ci 
on:
  push:
    branches:
      - documentation
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
            mkdocs==1.4.3
            mkdocs-autorefs==0.4.1
            mkdocs-material==9.1.15
            mkdocs-material-extensions==1.1.1
            mkdocstrings==0.20.0
            mkdocstrings-python==1.1.2
      - run: |
          cd NASLib_docs
          mkdocs gh-deploy --force
